name: Sync Bookings

on:
  push:
    paths:
      - 'data/bookings.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Commit atualizado via site
        run: |
          git config user.name "Agendamento Missionários"
          git config user.email "actions@github.com"
          git add data/bookings.json
          git commit -m "Atualização automática de agendamento" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}